# Generated by Django 2.1.7 on 2019-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician_name', models.CharField(max_length=200)),
                ('staff_id', models.CharField(max_length=200)),
                ('staff_mac_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=200)),
            ],
        ),
    ]
