# Generated by Django 2.2.1 on 2019-08-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrator'), (2, 'clinician'), (3, 'student')], null=True),
        ),
    ]
