# Generated by Django 2.2.1 on 2019-08-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Course'),
        ),
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Student')),
            ],
        ),
    ]
