# Generated by Django 2.1.7 on 2019-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeating',
            field=models.BooleanField(default=True),
        ),
    ]
