# Generated by Django 2.2.4 on 2019-09-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0002_auto_20190825_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=200)),
                ('tile_mac', models.CharField(max_length=200)),
            ],
        ),
    ]
