# Generated by Django 2.2.4 on 2019-09-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_tile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='clinician_mac',
        ),
        migrations.AddField(
            model_name='clinician',
            name='clinician_tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Tile'),
            preserve_default=False,
        ),
    ]
