# Generated by Django 2.1.7 on 2019-06-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_auto_20190603_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adttended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Event')),
            ],
        ),
        migrations.AddField(
            model_name='clinician',
            name='staff_email',
            field=models.CharField(default='fake123@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(default='fake123@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_percent',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(default='040069696969', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Student'),
        ),
    ]
