# Generated by Django 2.2.4 on 2019-10-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='jsonapi.Event'),
        ),
    ]
