# Generated by Django 2.2.4 on 2019-09-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0004_auto_20190904_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_events',
            field=models.ManyToManyField(through='jsonapi.StudentEvent', to='jsonapi.Event'),
        ),
    ]
